name: Deploy Flask App

on:
    workflow_dispatch:

jobs:

    deploy:
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER}}
        runs-on: self-hosted
    
        steps:

            - name: checkout Code
              uses: actions/checkout@v4
            
            - name: set up Docker Compose 
              uses: docker/setup-compose-action@v2
                
            - name: deploy with docker-compose
              run: docker compose up -d --build  

