# # Scan the dockerfile for issues & CVEs

name: Docker Lint

on:
    workflow_call:
jobs:
    check-dockerfile:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code 
              uses: actions/checkout@v4
            
            - name: Validate dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

