# This are workflow name
name: hello 

# Run on a automatic trigger, whenever change is pushed to a branch (Deployment)
on:
    workflow_dispatch: 
  # push:
  #   branches: [main]
  # paths defines, it controls which file/folder changes should trigger a workflow. 
    # paths:
    #   - '**.html'
    
# These are the jobs inside the workflow 
jobs:

  # This is the name of first job  
  greet:
    # This the github runner, each job runs on a runner 
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello dosto"

      - name: say hello to user
        run: echo "Hello $USER"
  # This is second job      
  show-version:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python, docker etc
        run: docker --version && python --version 
