# This are workfloe name
name: hello 

# Run on a trigger
on:
  push:
    branches: [main]

# These are the jobs inside the workflow 
jobs:

  # This is the name of the job
  greet:
    # This the github runner, each job runs on a runner 
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello dosto"

      - name: say hello to user
        run: echo "Hello $USER"
