#This is workflow name 
name: vaishnavi
# Runs on trigger 
on: 
  push:
    branches: [main]
    
# This is the list of jobs
jobs:
  # This is the first job name greet 
  greet:
    runs-on: ubuntu-latest  # we need to define where your job runs on
    steps:
      - name: greet to users
        run: echo "hello dosto"

      - name: ready for devOps
        run: echo "let's get ready for our devops journey"
        
  sign-in: # this is the second job
    runs-on: ubuntu-latest
    steps:
      - name: collect all the data from the students 
        run: echo "data is collected"
  
